export const CATEGORY_MAP = {
  AI: [
    "machine-learning",
    "deep-learning",
    "ai",
    "nlp",
    "computer-vision",
    "tensorflow",
    "pytorch",
    "keras",
    "scikit-learn",
    "openai",
    "llm",
    "transformers",
    "langchain",
    "vector-database"
  ],
  Frontend: [
    "react",
    "nextjs",
    "vue",
    "angular",
    "svelte",
    "tailwind",
    "css",
    "html",
    "typescript",
    "javascript",
    "frontend",
    "ui",
    "ux",
    "web-design",
    "styled-components",
    "sass"
  ],
  Backend: [
    "nodejs",
    "spring",
    "django",
    "fastapi",
    "flask",
    "express",
    "go",
    "rust",
    "postgresql",
    "mongodb",
    "redis",
    "mysql",
    "api",
    "graphql",
    "grpc",
    "microservices"
  ],
  DevOps: [
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "jenkins",
    "github-actions",
    "aws",
    "gcp",
    "azure",
    "devops",
    "ci-cd",
    "nginx",
    "prometheus",
    "grafana"
  ],
  Data: [
    "pandas",
    "data-science",
    "analytics",
    "spark",
    "hadoop",
    "sql",
    "big-query",
    "etl",
    "data-engineering",
    "data-visualization",
    "tableau",
    "numpy",
    "matplotlib"
  ]
};

// Language hints to help categorization when topics are missing
export const LANGUAGE_HINTS: Record<string, keyof typeof CATEGORY_MAP> = {
  Python: "AI",
  TypeScript: "Frontend",
  JavaScript: "Frontend",
  HTML: "Frontend",
  CSS: "Frontend",
  Java: "Backend",
  Go: "Backend",
  Rust: "Backend",
  "C++": "Backend",
  PHP: "Backend",
  Ruby: "Backend",
  Shell: "DevOps",
  HCL: "DevOps",
  SQL: "Data",
  R: "Data"
};
